name: simple_vcard_parser
version: 0.2.0
description: A simple and easy to use parser to extract information from a standard vCard string. Major vCard properties from versions 2.1, 3.0, 4.0 are supported.
repository: https://github.com/AmirElkess/simple_vcard_parser

environment:
  sdk: '>=2.0.0 <3.0.0'
